### 1. Listar regiones
GET http://localhost:8080/api/v1/cliente-service/clientes/regiones

###

### 2. Listar clientes (antes de crear)
GET http://localhost:8080/api/v1/cliente-service/clientes

###

### 3. Crear cliente (POST)
POST http://localhost:8080/api/v1/cliente-service/clientes
Content-Type: application/json

{
  "nombre": "Linus",
  "apellido": "Torvalds",
  "email": "linus@linux.org",
  "foto": "linus.jpg",
  "region": {
    "id": 1
  }
}

###

### 4. Consultar cliente por ID
GET http://localhost:8080/api/v1/cliente-service/clientes/1

###

### 5. Actualizar cliente por ID
PUT http://localhost:8080/api/v1/cliente-service/clientes/1
Content-Type: application/json

{
  "nombre": "Linus",
  "apellido": "Torvalds",
  "email": "linus@kernel.org",
  "foto": "linus-updated.jpg",
  "region": {
    "id": 1
  }
}

###

### 6. Eliminar cliente
DELETE http://localhost:8080/api/v1/cliente-service/clientes
Content-Type: application/json

{
  "id": 1
}