# ── Servidor HTTP ─────────────────────────────────────────────────────────────
server.port=8080

# ── Versión de la API ─────────────────────────────────────────────────────────
api.version=v1

# ── Conexión a PostgreSQL ─────────────────────────────────────────────────────
spring.datasource.url=jdbc:postgresql://localhost:5433/devdb
spring.datasource.username=devdb
spring.datasource.password=devdb
spring.datasource.driver-class-name=org.postgresql.Driver

# ── JPA / Hibernate ───────────────────────────────────────────────────────────
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true